export {
    WANT_DRAW,
    WANT_LOAD,
    LOAD,
    WANTS_SAVE,
    SAVE,
    TICK,
    WANTS_TOGGLE,
    PAUSE,
    RESUME,
    WANTS_TRAVEL_TIME,
    TRAVEL_TIME,
};


const WANT_DRAW = `WANT_DRAW`;
const WANT_LOAD = `WANT_LOAD`;
const LOAD = `LOAD`;
const WANTS_SAVE = `WANTS_SAVE`;
const SAVE = `SAVE`;
const TICK = `TICK`;
const WANTS_TOGGLE = `WANTS_TOGGLE`;
const PAUSE = `PAUSE`;
const RESUME = `RESUME`;
const WANTS_TRAVEL_TIME = `WANTS_TRAVEL_TIME`;
const TRAVEL_TIME = `TRAVEL_TIME`;

